apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-chatbot.componentFullname" (list $ "secrets") }}
  labels:
    {{- include "rag-chatbot.labels" $ | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  minio-root-user: {{ .Values.secrets.minioRootUser | quote }}
  minio-root-password: {{ .Values.secrets.minioRootPassword | quote }}
  keycloak-admin-password: {{ .Values.secrets.keycloakAdminPassword | quote }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
