apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chatbot.componentFullname" (list $ "backend") }}
  labels:
    {{- include "rag-chatbot.labels" $ | nindent 4 }}
    {{- include "rag-chatbot.selectorLabels" (list $ "backend") | nindent 4 }}
spec:
  selector:
    {{- include "rag-chatbot.selectorLabels" (list $ "backend") | nindent 4 }}
  ports:
    - port: {{ .Values.backend.containerPort }}
      targetPort: http
      name: http
