apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chatbot.componentFullname" (list $ "frontend") }}
  labels:
    {{- include "rag-chatbot.labels" $ | nindent 4 }}
    {{- include "rag-chatbot.selectorLabels" (list $ "frontend") | nindent 4 }}
spec:
  selector:
    {{- include "rag-chatbot.selectorLabels" (list $ "frontend") | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      name: http
